### PR TITLE
Feature/fix http 402

### PR DESCRIPTION
**Pull request by reto**
Blind fix for the error 402. Solution found by hint given by this comment https://github.com/pe-st/garmin-connect-export/issues/54#issuecomment-785177931
which references this comment: https://github.com/tcgoetz/GarminDB/issues/109#issuecomment-785047086

### CODE REVIEW

**Comment by telemaxx** [comment]
worked for me,  just tested.

**Comment by pierretamisier** [comment]
same here. works for me. just tested.

**Comment by mainzelM** [comment]
Yes, fixes the problem for me as well, thanks!

**Comment by pe-st** [comment]
Thanks a lot for this fast fix!

**Pull request merged**
