### PR TITLE
work-a-round if activityName contains non ASCII

### PR DESCRIPTION
**Pull request by jedie**
Yes, a silly work-a-round... But it work's with Python 2 ;)

btw. What's about a read port to only-Python-3 ?!?

### CODE REVIEW

**Comment by pe-st** [comment]
Hello @jedie 
What characters do you have problems with? I have plenty of umlauts that just work fine...
Unfortunately I can't test right now because of https://github.com/pe-st/garmin-connect-export/issues/14 and I have no time today to investigate it.

As for Python 3: I see no urgency, but YMMV. I think for all the Mac users it's still easier to use Python 2.7 (High Sierra still comes with 2.7: https://docs.python-guide.org/starting/install3/osx/, don't know about Mojave yet). For Windows the last time I looked no Python is included and for Linux I have no idea which distro ships with which Python, so for Windows and Linux the Python version might make no difference, but for most Mac users it does.

**Comment by jedie** [comment]
Yes, it was Umlauts: e.g.: "Düsseldorf" ;)

Python 2.7 will not be maintained past 2020: https://www.python.org/dev/peps/pep-0373/
On Linux: IMHO all current distribution has python 3 installed and for some time now all used python 3 as default and didn't install python 2 anymore.

For Windows: It's not problem to install Python 3

So: At least it would be good to support python 3, too.

**Comment by pe-st** [comment]
I have no problems displaying umlauts or even emojis. I added this nice emoji in the Garmin Connect web interface for my last activity

pavillon-emoji

and it shows up just fine in the console:

    Finished activity request ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Garmin Connect activity: [2958378924] Biel 🏛 Pavillon

Here's a screenshot of my console:

console-emoji

So it must be your console or terminal program that can't handle umlauts, and doesn't need fixing in the script.

**Comment by jedie** [comment]
> So it must be your console or terminal program that can't handle umlauts, and doesn't need fixing in the script.

Maybe...

**Pull request closed without merging**
