### PR TITLE
Remove Python2 leftovers

### PR DESCRIPTION
**Pull request by bxsx**
# Story

This PR removes all traces of Python2 support

# Background

Python2 is not supported since [v3.2.0](https://github.com/pe-st/garmin-connect-export/releases/tag/v3.2.0) (via 525e3fd). Rationales: #64

# Details

- Removed deprecated conditional statements
- Refactoring the codebase to the Python 3 standard
- Updated `CONTRIBUTING.md`
- Added .swp extension to `.gitignore` file _(unrelated to PR)_

### Note:
Python 2 is still referenced in the documentation. These references are intended to be kept for some time.
https://github.com/pe-st/garmin-connect-export/blob/0b114e722b73da04e905a5c50caf4b8b7edeaff8/CONTRIBUTING.md?plain=1#L11-L16

### CODE REVIEW

**Comment by pe-st** [comment]
Thank you for your PR!

I see you also cleaned up some code that it not related to Python 3, but to pylint. I didn't keep the code pylint-clean during the transition period Python 2..3, so there is no automated linting yet.

The documentation for GitHub Actions for Python mentions flake8 (but not pylint), so flake8 is probably the preferred/a good enough tool to keep the style clean. I would like to have some tool in Github Actions to help people like me that don't use python daily to point at things that could be done better. And with removing python2 code it becomes once more feasible to use such a tool.

I have added a [feature branch](https://github.com/pe-st/garmin-connect-export/tree/feature/flake8) with a draft on how flake8 could be integrated.

What do you think about it, @bxsx ?

**Comment by pe-st** [comment]
> Take a look on the diffs output. I can open a PR with the black integration and required changes, and maybe manually review the style, so I can fix or compact something.

From what I saw black is just a formatter, not a static analyzer. I think it is maybe a little bit too opinionated (in some cases where I added newlines for readability, black removed them etc)

I hope I'll have some more time in the following weeks to look into the available code checkers, but I'll merge your PR before

**Comment by bxsx** [comment]
> In that case, the recommended tool is `mypy`, but I'm afraid the code base is not ready for this.

So I ran `mypy` and fixed the reported issues in 30b6b0b. It runs successfully now, but without supported `typing` we don't take the real advantage of `mypy`. See output when run with `--strict` option: `Found 334 errors in 4 files (checked 4 source files)`

**Comment by pe-st** [comment]
I rebased and merged the PR. Thanks again!

**Comment by bxsx** [comment]
Thanks @pe-st!

One question, why does GitHub show the PR as rejected? I see commits in the `master` branch though..

**Comment by pe-st** [comment]
> Thanks @pe-st!
> 
> One question, why does GitHub show the PR as rejected? I see commits in the `master` branch though..

I rebased your commits in my local workspace, not via the Github interface, and closed the PR manually. Maybe I missed some option/button to declare the PR as merged. I always struggle with the Github interface, at work I'm used to Gitlab...

**Comment by bxsx** [comment]
Gotcha! Well, seems like GitHub doesn't have a way to know if rebased commits are attached to any PR. I think that's why GH allows to rebase and merge via UI interface. Some docs on the topic: [Supported merge options by GitHub](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges) and [Merge UI instructions](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request)

PS. GitLab is very nice too!

**Pull request closed without merging**
