### PR TITLE
Implementing Feature Request #28: workflowdirectory

### PR DESCRIPTION
**Pull request by telemaxx**
Implementing: https://github.com/pe-st/garmin-connect-export/issues/28

News:

- new parameter `--workflowdirectory` see: https://github.com/pe-st/garmin-connect-export/issues/28
- new parameters  `--wdesc`  `--wdevice` for naming workflow files
- using shutil.move instead od os.rename its more robust when file already exist
- when using this script too often, just print a short message instead of "raise"
- at end of the script printout a summary

### CODE REVIEW

**Comment by telemaxx** [comment]
Tests done:
**---Windows:--**
**P3: fitfiles with unzip**
`c:\Python3\python.exe C:\Users\top\BTSync\SA5\qpython\scripts\Garmin-Connect-Export-pest\gcexport.py  -c 10 -f original  --username "myname"  --password "mypasswd" --directory "C:\public\gps" --unzip`

**P3: gpx files**
`c:\Python3\python.exe C:\Users\top\BTSync\SA5\qpython\scripts\Garmin-Connect-Export-pest\gcexport.py  -c 5 -f gpx --username "myname"  --password "mypasswd" --directory "C:\public\gps"`

**P3: tcx files**
`c:\Python3\python.exe C:\Users\top\BTSync\SA5\qpython\scripts\Garmin-Connect-Export-pest\gcexport.py  -c 5 -f tcx --username "myname"  --password "mypasswd" --directory "C:\public\gps"`

**P3: gpx files in subfolder**
`c:\Python3\python.exe C:\Users\top\BTSync\SA5\qpython\scripts\Garmin-Connect-Export-pest\gcexport.py  -c 5 -f gpx   --username "myname"  --password "mypasswd"  --directory "C:\public\gps" -s gpx`

**P3: tcx files in subfolder**
`c:\Python3\python.exe C:\Users\top\BTSync\SA5\qpython\scripts\Garmin-Connect-Export-pest\gcexport.py  -c 5 -f tcx   --username "myname"  --password "mypasswd"  --directory "C:\public\gps" -s tcx`

**P3: some more advanced parameter**
`c:\Python3\Python.exe C:\Users\top\BTSync\SA5\qpython\scripts\Garmin-Connect-Export-pest\gcexport.py  -c 12 -f tcx --username "myname"  --password "mypasswd"--directory "C:\public\gps" --unzip --desc 12 -fp -sa 8 -s tcx`

**P3: fit files in workflowmode with naming options**
`c:\Python3\python.exe C:\Users\top\BTSync\SA5\qpython\scripts\Garmin-Connect-Export-pest\gcexport.py  -c 10 -f original  --username "myname"  --password "mypasswd" --directory "C:\public\gps"  --workflowdirectory c:\public --unzip --wdesc 10 --wdevice 5`

**P2: fitfiles with unzip**
`c:\Pypy2\pypy.exe C:\Users\top\BTSync\SA5\qpython\scripts\Garmin-Connect-Export-pest\gcexport.py  -c 10 -f original   --username "myname"  --password "mypasswd"  --directory "C:\public\gps" --unzip`

**P2: gpx files**
`c:\Pypy2\pypy.exe C:\Users\top\BTSync\SA5\qpython\scripts\Garmin-Connect-Export-pest\gcexport.py  -c 10 -f gpx  --username "myname"  --password "mypasswd" --directory "C:\public\gps"`

**P2: tcx files with some options**
`c:\Pypy2\pypy.exe C:\Users\top\BTSync\SA5\qpython\scripts\Garmin-Connect-Export-pest\gcexport.py  -c 10 -f tcx   --username "myname"  --password "mypasswd" --directory "C:\public\gps" --unzip --desc 12 -fp -sa 8 -s tcx`

**P2: gpx files in subfolder**
`c:\Pypy2\pypy.exe C:\Users\top\BTSync\SA5\qpython\scripts\Garmin-Connect-Export-pest\gcexport.py  -c 5 -f gpx   --username "myname"  --password "mypasswd"  --directory "C:\public\gps" -s gpx`

**P2: tcx files in subfolder**
`c:\Pypy2\pypy.exe C:\Users\top\BTSync\SA5\qpython\scripts\Garmin-Connect-Export-pest\gcexport.py  -c 5 -f tcx   --username "myname"  --password "mypasswd"  --directory "C:\public\gps" -s tcx`

**P2: tcx file in subfolder with many options**
`c:\Pypy2\pypy.exe C:\Users\top\BTSync\SA5\qpython\scripts\Garmin-Connect-Export-pest\gcexport.py  -c 12 -f tcx --username "myname"  --password "mypasswd"--directory "C:\public\gps" --unzip --desc 12 -fp -sa 8 -s tcx`

**P2: fitfiles with unzip in workflowmode with naming options**
`c:\Pypy2\pypy.exe C:\Users\top\BTSync\SA5\qpython\scripts\Garmin-Connect-Export-pest\gcexport.py  -c 10 -f original   --username "myname"  --password "mypasswd"  --directory "C:\public\gps"  --workflowdirectory c:\public --unzip --wdesc 10 --wdevice 5`

**-- Linux --**
**Python 3**
`/usr/bin/python3 $garmin_base_dir/gcexport.py -c 5 -f original -v --username $garmin_user --password $garmin_pw --directory $garmin_fit_dir --workflowdirectory $garmin_mytourbook_fit_dir --unzip  --wdesc 25 --wdevice 8`

**Comment by telemaxx** [comment]
Summary Output:

```
....
Garmin Connect activity (16\17) [4655548358] Hannover Rennradfahren
        2020-03-14T17:00:07+01:00, 01:03:56, 10.658km
Garmin Connect activity (17\17) [4653712685] Hannover Rennradfahren
        2020-03-12T17:01:41+01:00, 02:25:49, 12.513km
Total Requested....17
Total Downloaded...17
Total Copied.......7
Total Skipped......10
Done!
```

**Comment by pe-st** [comment]
```
> Total Requested..........27
> Total Downloaded.........2
> Total Copied(workflow)...0
> Total Skipped............25
> Done!
```
I like this summary 😄

**Comment by pe-st** [comment]
>     * new parameters  `--wdesc`  `--wdevice` for naming workflow files

To avoid too many options just dealing with the file name (there are already `--desc` and `--fileprefix`) I would like to take a different approach with some kind of format string, e.g. an option `-nt <tmpl>`/`--nametemplate <tmpl>` where `<tmpl>` is a simple format string inspired by Pythons `format()` function.

If you want a different filename for the workflow (would that be needed?), an option `-wnt <tmpl>`/`--wnametemplate <tmpl>` could be defined using the same algorithm.

Possible examples (untested)

- `--desc` could be implemented by a template `activity_{activityId}_{activityName}`
- `--fileprefix` could be implemented by a template
  `{startTimeLocal:%Y%m%d_%H%M%S}_activity_{activityId}`
- `--wdevice` could be implemented by a template `activity_{device}`

What do you think?

**Comment by telemaxx** [comment]
> If you want a different filename for the workflow (would that be needed?), an option `-wnt <tmpl>`/`--wnametemplate <tmpl>` could be defined using the same algorithm.

this is a good idea.
yesterday i thought, would be nice having also the recording length kilometers inside the filename... with templates it would be flexible and without many new options.

If possible, i would like to have workflow filenames without that cryptic activity id.
maybe with `-wnt <tmpl>` option or just `-nt <tmpl>` when we suppress the activity id for workflow filenames.
for the "normal" files, i think, we need the id to detect if activities are already downloaded. or?

we could start with just  `-nt <tmpl>`
but it could be complicate to implement.
did you have a plan how to do this?

**Comment by telemaxx** [comment]
updating my fork and send a new PR

**Pull request closed without merging**
